- name: 'ensuring directories'
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - ~/.config
    - ~/.cows

- name: 'copying bash files'
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: files/bash/bashrc
      dest: ~/.bashrc
    - src: files/bash/bash_aliases
      dest: ~/.bash_aliases
    - src: files/bash/profile
      dest: ~/.profile
    - src: files/bash/liquidpromptrc
      dest: ~/.config/liquidpromptrc
    - src: files/bash/liquidprompt/liquidprompt
      dest: ~/.bash_prompt
    - src: files/bash/cows/
      dest: ~/.cows/
    - src: files/git/gitconfig
      dest: ~/.gitconfig
    - src: files/git/gitignore
      dest: ~/.gitignore
