- name: 'ensuring directories'
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - "{{ home }}/.config"
    - "{{ home }}/.cows"

- name: 'copying bash files'
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: files/bash/bashrc
      dest: "{{ home }}/.bashrc"
    - src: files/bash/bash_aliases
      dest: "{{ home }}/.bash_aliases"
    - src: files/bash/profile
      dest: "{{ home }}/.profile"
    - src: files/bash/liquidpromptrc
      dest: "{{ home }}/.config/liquidpromptrc"
    - src: files/bash/liquidprompt/liquidprompt
      dest: "{{ home }}/.bash_prompt"
    - src: files/bash/cows/
      dest: "{{ home }}/.cows/"
    - src: files/git/gitconfig
      dest: "{{ home }}/.gitconfig"
    - src: files/git/gitignore
      dest: "{{ home }}/.gitignore"
