#!/bin/bash
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias l='ls -lh'
alias la='ls -A'
alias ll='ls -lh'
alias lla='ls -lhA'
alias lg='ls -A | grep'
alias llg='ls -lhA | grep'
alias clean='find . \( -name "*.pyc" -o -name "*~" \) -delete; git clean -fd 2> /dev/null'
alias rsync='rsync --exclude="*.o" --exclude="*.so" --exclude="*~" --exclude="*.swp" --exclude="*.pyc" --exclude=".git/*"'
alias bim="echo 'BIM !!!'"
alias vul="vim"
alias voù="vim"
alias cim="vim"

grepk() {
    grep -ER \
        --binary-files=without-match \
        --exclude-dir=".webassets-cache" \
        --exclude-dir=".git" \
        --exclude-dir="venv" \
        --exclude-dir="build" \
        --exclude-dir="static" \
        --exclude-dir="site-packages" \
        --exclude-dir="gen"  \
        --exclude-dir=".mypy_cache" \
        --exclude-dir="__snapshots__" \
        --exclude-dir="dist" \
        --exclude-dir="cypress" \
        --exclude-dir="node_modules" \
        --exclude="tslint.json" \
        --exclude="*.min.js" \
        --exclude="*.pyc" \
        --exclude="*.swp" \
        --exclude="*~" \
        "$*" .
}
# Chercher dans les process et non pas le club de foot
psg() {
    ps aux |  sed -e "/grep --color=auto $1/d" | grep "$*"
}

vimgrepk() {
    vim $(grepk "$*" |sed -e "s/:.*//g"|uniq)
}

vimOgrepk() {
    vim -O $(grepk "$*" |sed -e "s/:.*//g"|uniq)
}
wo() {
    cd ~/devel/$1/
    has_src=$(test -d src)
    if [ -f Pipfile ] && $has_src; then
        pipenv shell cd src/
    elif [ -f Pipfile ]; then
        pipenv shell
    fi
}
