- name: 'ensuring directories'
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ dotfile_user }}"
    group: "{{ group }}"
    force: true
  with_items:
    - "{{ home }}/.vim/autoload"
    - "{{ home }}/.vim/bundle"
    - "{{ home }}/.vim/after"

- name: 'copy vim conf'
  synchronize:
    src: files/vim/vimrc
    dest: "{{ home }}/.vimrc"
    archive: True
    delete: True
    owner: False
    group: False
    rsync_path: >-
      {%- if become == True -%}
        sudo rsync
      {%- else -%}
        rsync
      {%- endif -%}

- name: 'installing pathogen'
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "{{ home }}/.vim/autoload/pathogen.vim"

- name: 'installing various vim plugins'
  synchronize:
    src: "files/vim/{{ item.name|dirname }}/"
    dest: "{{ home }}/.vim/{{ item.type }}/"
    archive: True
    delete: True
    owner: False
    group: False
    rsync_path: >-
      {%- if become == True -%}
        sudo rsync
      {%- else -%}
        rsync
      {%- endif -%}
  with_items:
    - {name: syntastic, type: bundle}
    - {name: ctrlp.vim, type: bundle}
    - {name: tlib_vim, type: bundle}
    - {name: vim-addon-mw-utils, type: bundle}
    - {name: vim-colors-solarized, type: bundle}
    - {name: vim-fugitive, type: bundle}
    - {name: pydoc.vim, type: after}
